### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by equihuam** [kshirley/LDAtools#8]
I am working in windows 8.1 (64) with R version 3.1.1 (2014-07-10).  Tried to install your package but got this message:

Aviso: comando ejecutado 'make -f "C:/PROGRA~1/R/R-31~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-31~1.1/share/make/winshlib.mk" SHLIB="LDAtools.dll" OBJECTS="lda.o ldapredict.o minperplex.o"' tiene estatus 127
ERROR: compilation failed for package 'LDAtools'
- removing 'C:/Users/Miguel/Documents/R/win-library/3.1/LDAtools'
  Error: Command failed (1)
